import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./_components/footer";
import Navbar from "./_components/navbar";
import Session from "@/context/session-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Session>
          <div className="flex flex-col w-11/12 h-screen max-w-screen-lg mx-auto">
            <Navbar />
            <main className="flex-grow">{children}</main>
          </div>
          <Footer />
        </Session>
      </body>
    </html>
  );
}
